### ISSUE TITLE
role.sh, missing?

### ISSUE THREAD

**Issue by brizzbane** [neumark/tw5-firebase#1]
I made it to the last step.

The last instruction of https://neumark.github.io/tw5-firebase/authentication_and_permissions.html

says to run:

./scripts/role.sh grant --email foo@bar.com --role admin

I don't see this locally.  I'm not familiar at all with firebase.  Was it built, and there is a way to access console on firebase (I'm thinking like SSH access of VM compute instances)?

Or is it missing?

Appreciate your help!

**Comment by neumark** [comment]
Hey Brizz!
So sorry about not updating the docs, doing that real soon.
I've upgraded role.sh to the more general cli.sh.
The new syntax is:
./scripts/cli.sh  setrole foo@bar.com admin

Let me know how it goes!!!

**Comment by neumark** [comment]
Fixed this in the documentation, hopefully won't cause issues for anyone else.
Thanks for the heads up!
